# eamxx fails with gcc 13
c_compiler_version:       # [linux]
  - 12                    # [linux]
cxx_compiler_version:     # [linux]
  - 12                    # [linux]
fortran_compiler_version: # [linux]
  - 12                    # [linux]

# default to using mpich, else openmpi
# scorpio needs an mpi...
mpi:
  - openmpi
  - mpich

# set target to mahf708
# so that we can rerender for gha
channel_sources:
  - conda-forge
channel_targets:
  - mahf708 main
