{% set build = 0 %}

# recipe-lint fails if mpi is undefined
{% set mpi = mpi or 'mpich' %}
{% if mpi == "mpich" %}
  # prioritize mpich via build number
  {% set build = build + 100 %}
{% endif %}

{% set mpi_prefix = "mpi_" + mpi %}

{% if mpi == "mpi_serial" %}
  # we want to use the "nompi" versions of dependencies
  {% set mpi_dep_prefix = "nompi" %}
{% else %}
  {% set mpi_dep_prefix = mpi_prefix %}
{% endif %}

package:
  name: pyeamxx
  version: 0.0.1.dev5

source:
  url: https://github.com/mahf708/full-scream/releases/download/commit-9a6dfda/9a6dfda-full.tar.gz
  sha256: 6150f16bbdf8407e9ecc4dee3bd9d9f64e9955decd796f27d6d53f2d219e5962

build:
  number: {{ build }}
  skip: true # [win]
  string: {{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}

requirements:
  build:
    - cmake
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - {{ mpi }}  # [mpi == 'openmpi' and build_platform != target_platform]
  host:
    - python
    - pybind11
    - setuptools
    - build
    - spdlog
    - fmt
    - yaml-cpp
    - {{ mpi }}
    - hdf5
    - hdf5 * {{ mpi_dep_prefix }}_*
    - libnetcdf
    - libnetcdf * {{ mpi_dep_prefix }}_*
    - netcdf-cxx4
    - netcdf-cxx4 * {{ mpi_dep_prefix }}_*
    - netcdf-fortran
    - netcdf-fortran * {{ mpi_dep_prefix }}_*
    - libpnetcdf  # [mpi != 'mpi_serial']
    - libpnetcdf * {{ mpi_dep_prefix }}_*  # [mpi != 'mpi_serial']
    - python
    - numpy
    - mpi4py
  run:
    - {{ pin_compatible('spdlog', max_pin='x.x') }}
    - {{ pin_compatible('fmt', max_pin='x.x') }}
    - {{ pin_compatible('yaml-cpp', max_pin='x.x') }}
    - python
    - {{ pin_compatible('numpy', max_pin='x.x') }}
    - mpi4py

about:
  home: https://github.com/E3SM-Project/scream
  summary: Python wrapper for EAMxx

extra:
  recipe-maintainers:
    - scream-team
