{% set build = 0 %}
{% set mactag = "anymachine" %}

# recipe-lint fails if mpi is undefined
{% set mpi = mpi or 'mpich' %}
{% if mpi == "mpich" %}
  # prioritize mpich via build number
  {% set build = build + 100 %}
{% endif %}

{% set mpi_prefix = "mpi_" + mpi %}

{% if mpi == "mpi_serial" %}
  # we want to use the "nompi" versions of dependencies
  {% set mpi_dep_prefix = "nompi" %}
{% else %}
  {% set mpi_dep_prefix = mpi_prefix %}
{% endif %}

package:
  name: pyeamxx
  version: 0.0.1

source:
  url: https://github.com/mahf708/full-scream/releases/download/commit-b8e86ba/b8e86ba-full.tar.gz
  sha256: d39f4d81232a2acc29f95b355677ef9645fa40585446d76fec87cc8c8c2d5d64

build:
  number: {{ build }}
  skip: true # [win]
  skip: true # [osx]
  string: {{ mpi_prefix }}_py{{ CONDA_PY }}_h{{ PKG_HASH }}_{{ build }}_{{ anymachine }}

requirements:
  build:
    - cmake
    - make
    - wget
    - unzip
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - {{ mpi }}  # [mpi == 'openmpi' and build_platform != target_platform]
  host:
    - python
    - pybind11
    - setuptools
    - build
    - wheel
    - spdlog
    - fmt
    - yaml-cpp
    - {{ mpi }}
    - hdf5
    - hdf5 * {{ mpi_dep_prefix }}_*
    - libnetcdf
    - libnetcdf * {{ mpi_dep_prefix }}_*
    - netcdf-cxx4
    - netcdf-cxx4 * {{ mpi_dep_prefix }}_*
    - netcdf-fortran
    - netcdf-fortran * {{ mpi_dep_prefix }}_*
    - libpnetcdf  # [mpi != 'nompi']
    - libpnetcdf * {{ mpi_dep_prefix }}_*  # [mpi != 'nompi']
    - python
    - numpy
    - mpi4py
  run:
    - {{ pin_compatible('spdlog', max_pin='x.x') }}
    - {{ pin_compatible('fmt', max_pin='x.x') }}
    - {{ pin_compatible('yaml-cpp', max_pin='x.x') }}
    - python
    - {{ pin_compatible('numpy', max_pin='x.x') }}
    - mpi4py
    - pyyaml

about:
  home: https://github.com/E3SM-Project/scream
  summary: Python wrapper for EAMxx

extra:
  recipe-maintainers:
    - scream-team
