conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
provider:
  linux_64: github_actions
github_actions:
  store_build_artifacts: true
  free_disk_space: true
  artifact_retention_days: 30
